DROP TABLE IF EXISTS url_checks;

DROP TABLE IF EXISTS urls;

CREATE TABLE urls(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) UNIQUE,
	created_at DATE default NOW()
);

CREATE TABLE url_checks(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	url_id BIGINT REFERENCES urls(id) NOT NULL,
	status_code BIGINT,
	h1 VARCHAR(255),
	title VARCHAR(255),
	description TEXT,
	created_at DATE default NOW()
);